CREATE TABLE MsProduct(
ProductID CHAR(7) PRIMARY KEY NOT NULL,
ProductName VARCHAR(255) NOT NULL,
ProductPrice INT NOT NULL,
Quantity INT NOT NULL,
)

CREATE TABLE Category(
CategoryID CHAR(7) PRIMARY KEY NOT NULL
)

CREATE TABLE MsSupplier(
SupplierID CHAR(7) PRIMARY KEY NOT NULL,
SupplierName VARCHAR(255) NOT NULL,
[Address] VARCHAR(255) NOT NULL,
PhoneNumber VARCHAR(255) NOT NULL,
PaymentTerms VARCHAR(255) NOT NULL
)